version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wakandata
      POSTGRES_PASSWORD: wakandata
      POSTGRES_DB: mlopsvn-marathon
    ports:
      - 5432:5432
